import { listMarketInstruments } from "@/lib/market/market-instruments";
import { SEED_WATCHLIST } from "@/lib/watchlist/types";

/** Curated, content-complete discovery set. Never derive sitemap URLs from user input. */
const CORE_EQUITIES = [
  "AAPL",
  "MSFT",
  "NVDA",
  "AMZN",
  "GOOG",
  "META",
  "TSLA",
  "AVGO",
  "ORCL",
  "NFLX",
  "AMD",
  "INTC",
  "QCOM",
  "CRM",
  "ADBE",
  "NOW",
  "PLTR",
  "IBM",
  "CSCO",
  "MU",
  "JPM",
  "BAC",
  "GS",
  "MS",
  "V",
  "MA",
  "BRK-B",
  "BLK",
  "SCHW",
  "HOOD",
  "WMT",
  "COST",
  "HD",
  "MCD",
  "NKE",
  "DIS",
  "KO",
  "PEP",
  "SBUX",
  "AMZN",
  "LLY",
  "JNJ",
  "UNH",
  "MRK",
  "ABBV",
  "PFE",
  "TMO",
  "GILD",
  "VRTX",
  "REGN",
  "XOM",
  "CVX",
  "COP",
  "SLB",
  "BA",
  "CAT",
  "GE",
  "HON",
  "LMT",
  "RTX",
] as const;

export function listSeoTickers(): string[] {
  return [
    ...new Set([
      ...CORE_EQUITIES,
      ...SEED_WATCHLIST.map((entry) => entry.ticker.toUpperCase()),
      ...listMarketInstruments().map((entry) => entry.ticker.toUpperCase()),
    ]),
  ].sort();
}
