import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
function read(path: string) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

describe("Pulse heatmap universe", () => {
  it("keeps even more-markets groups and no page hero", () => {
    const route = read("src/lib/market/pulse-data.ts");
    const page = read("src/components/market/PulseBoard.tsx");

    expect(route).toContain('ticker: "UNG"');
    expect(route).toContain('category: "Commodity"');
    expect(route).not.toContain('category: "Themes"');
    expect(route).not.toContain("SOL-USD");
    expect(page).not.toContain('title="Themes"');
    expect(page).not.toContain("themeMarkets");
    expect(page).not.toContain("MarketNarrativeDriversPanel");
    expect(page).not.toContain("ProductStage");
    expect(page).not.toContain("pulseHeroCopy");
    expect(page).not.toContain("headlineMaxLines");
    expect(page).not.toContain("hero.summary");
    expect(page).not.toContain("regimeSummary");
    expect(page).toContain("CommodityScoreboard");
    expect(page).not.toContain('title="Commodities"');
    expect(page).toContain("CryptoBoard");
    expect(page).toContain("SurfaceSlicer");
    expect(page).toContain("SectorScoreboard");
    expect(page).toContain("InternationalScoreboard");
    expect(page).not.toContain("GlobalMarketsHeatmap");
    expect(page).toContain("MarketMovesPanel");
    expect(page).not.toContain("showDecisionCard");
    expect(page).not.toContain("ViewSwitcher");
    expect(page).not.toContain("PULSE_TABS");
    expect(page).not.toContain("pulse-tab-indexes");
    expect(page).not.toContain("pulse-panel-trending");
  });

  it("does not treat Trending as a watchlist chip editor", () => {
    const panel = read("src/components/market/MarketMovesPanel.tsx");

    expect(panel).toContain("MarketMoversBoard");
    expect(panel).toContain("splitMarketMovers");
    expect(panel).not.toContain("StockHeatmap");
    expect(panel).not.toContain("TrendingManageChips");
    expect(panel).not.toContain("wl-manage-row");
    expect(panel).not.toContain("PulseDecisionCard");
    expect(panel).not.toContain("showDecisionCard");
  });

  it("renders Markets as gauges + indexes + commodities + sectors; slicer is Markets · Movers · Crypto · Intl", () => {
    const page = read("src/components/market/PulseBoard.tsx");
    const board = read("src/components/market/IndexScoreboard.tsx");
    const gauges = read("src/components/market/PulseMacroGauges.tsx");
    const css = read("src/app/globals.css");
    const marketsBlockStart = page.indexOf('view === "markets"');
    const gaugesStart = page.indexOf("<PulseMacroGauges", marketsBlockStart);
    const indexesStart = page.indexOf("<IndexScoreboard", marketsBlockStart);
    const commoditiesStart = page.indexOf("<CommodityScoreboard", marketsBlockStart);
    const sectorsStart = page.indexOf("<SectorScoreboard", marketsBlockStart);
    const marketsBlockEnd = page.indexOf('view === "movers"', marketsBlockStart + 1);
    const marketsBlock = page.slice(marketsBlockStart, marketsBlockEnd);
    const indexesBlock = page.slice(gaugesStart, commoditiesStart);
    const slicerStart = page.indexOf("PULSE_VIEWS");
    const slicerEnd = page.indexOf("];", slicerStart);
    const slicerBlock = page.slice(slicerStart, slicerEnd);
    expect(page).toContain('className="pulse-view-slicer"');
    expect(page).toContain('label: "Markets"');
    expect(page).toContain('label: "Movers"');
    expect(page).toContain('label: "Crypto"');
    expect(page).toContain('label: "Intl"');
    expect(page).not.toContain('label: "Commodities"');
    expect(page).not.toContain('label: "Sectors"');
    expect(page).not.toContain('label: "International"');
    expect(slicerBlock.indexOf('label: "Movers"')).toBeLessThan(slicerBlock.indexOf('label: "Crypto"'));
    expect(slicerBlock.indexOf('label: "Crypto"')).toBeLessThan(slicerBlock.indexOf('label: "Intl"'));
    expect(gaugesStart).toBeGreaterThan(-1);
    expect(indexesStart).toBeGreaterThan(-1);
    expect(commoditiesStart).toBeGreaterThan(-1);
    expect(sectorsStart).toBeGreaterThan(-1);
    expect(gaugesStart).toBeLessThan(indexesStart);
    expect(indexesStart).toBeLessThan(commoditiesStart);
    expect(commoditiesStart).toBeLessThan(sectorsStart);
    expect(marketsBlock).toContain("SectorScoreboard");
    expect(marketsBlock).toContain("CommodityScoreboard");
    expect(marketsBlock).not.toContain("MarketMovesPanel");
    expect(marketsBlock).not.toContain("CryptoBoard");
    expect(marketsBlock).not.toContain("pulse-more-markets");
    expect(page).toContain('view === "movers"');
    expect(page).toContain('view === "crypto"');
    expect(page).toContain('view === "international"');
    expect(page).not.toContain('view === "commodities"');
    expect(page).not.toContain('view === "sectors"');
    expect(page).not.toContain("ViewSwitcher");
    expect(page).not.toContain("PULSE_TABS");
    expect(page).not.toContain("pulse-panel-trending");
    expect(page).not.toContain('id="industries"');
    expect(page).toContain("PulseMacroGauges");
    expect(page).toContain("IndexScoreboard");
    expect(page).toContain("CommodityScoreboard");
    expect(page).toContain("MarketMovesPanel");
    expect(indexesBlock).toContain("sessionLabel={data.sessionLabel}");
    expect(indexesBlock).not.toContain("HeatTile");
    expect(indexesBlock).not.toContain("HeatmapGrid");
    expect(indexesBlock).not.toContain("ProductStage");
    expect(gauges).toContain("pulse-gauge-grid");
    expect(gauges).not.toContain("ProductStage");
    expect(board).toContain("pulse-index-row");
    expect(board).toContain("pulse-index-session");
    expect(board).toContain("showSessionMoves");
    expect(board).toContain("SessionQuoteStack");
    expect(board).toContain("extendedNoTrades");
    expect(board).not.toContain("pulse-move-bar");
    expect(board).not.toContain("moverBarHeight");
    expect(board).not.toContain("pulse-index-sessions");
    expect(board).not.toContain("IndexSessionMoves");
    expect(board).toContain('title="Commodities"');
    expect(board).toMatch(/CommodityScoreboard[\s\S]*showSessionMoves/);
    expect(board).toContain("SectorScoreboard");
    expect(board).toContain("InternationalScoreboard");
    expect(board).not.toContain("stock-heat-session");
    expect(board).not.toContain("HeatTile");
    expect(css).toContain(".pulse-index-row");
    expect(css).toContain(".session-quote");
    expect(css).toContain(".session-quote-extended");
    expect(css).not.toContain(".pulse-move-bar");
    expect(css).toContain(".pulse-gauge-grid");
    expect(css).toContain(".pulse-movers-stack");
    expect(css).toMatch(/\.pulse-gauge-card\s*\{[^}]*background:\s*transparent/s);
    expect(css).toMatch(/\.market-tape\s*\{[^}]*background:\s*transparent/s);
    expect(css).toMatch(/\.market-tape\s*\{[^}]*border-top:\s*1px solid/s);
    expect(css).toMatch(/\.market-tape-item \+ \.market-tape-item\s*\{[^}]*border-left:\s*0/s);
    expect(css).toContain(".market-tape-item + .market-tape-item::before");
    expect(css).toContain('content: "·"');
    expect(css).toMatch(/\.pulse-gauge-kicker\s*\{[^}]*text-align:\s*center/s);
    expect(css).not.toContain(".pulse-index-sessions");
  });

  it("expands Crypto beyond BTC/ETH without bringing Solana back to Pulse", () => {
    const route = read("src/lib/market/pulse-data.ts");
    const board = read("src/components/market/CryptoBoard.tsx");
    expect(route).toContain("XRP-USD");
    expect(route).toContain("DOGE-USD");
    expect(route).toContain("ADA-USD");
    expect(route).not.toContain('category: "Crypto Equity"');
    expect(route).not.toContain("COIN");
    expect(route).not.toContain("SOL-USD");
    expect(board).not.toContain("Related");
    expect(board).not.toContain("CryptoRelatedStrip");
  });
});

describe("Pulse slicer hosts Markets, Movers, Crypto, Intl", () => {
  it("hosts scoreboards on Pulse slicer views and redirects legacy Menu routes", () => {
    const nav = read("src/lib/nav-config.ts");
    const page = read("src/components/market/PulseBoard.tsx");
    const sectors = read("src/app/sectors/page.tsx");
    const international = read("src/app/international/page.tsx");
    const sectorsLayout = read("src/app/sectors/layout.tsx");
    const internationalLayout = read("src/app/international/layout.tsx");

    expect(nav).not.toContain('href: "/sectors"');
    expect(nav).not.toContain('href: "/international"');
    expect(page).toContain('view === "movers"');
    expect(page).toContain('view === "crypto"');
    expect(page).toContain('view === "international"');
    expect(page).toContain('label: "Movers"');
    expect(page).toContain('label: "Crypto"');
    expect(page).toContain('label: "Intl"');
    expect(page).not.toContain('label: "Commodities"');
    expect(page).toContain("SectorScoreboard");
    expect(page).toContain("CommodityScoreboard");
    expect(page).toContain("InternationalScoreboard");
    expect(page).toContain("CryptoBoard");
    expect(page).toContain("sessionLabel={data.sessionLabel}");
    expect(sectors).toContain('permanentRedirect("/pulse")');
    expect(international).toContain('permanentRedirect("/pulse?view=international")');
    expect(sectorsLayout).toContain("pageMetadata");
    expect(sectorsLayout).toContain('path: "/pulse"');
    expect(sectorsLayout).toContain("index: false");
    expect(internationalLayout).toContain("pageMetadata");
    expect(internationalLayout).toContain('path: "/pulse?view=international"');
    expect(internationalLayout).toContain("index: false");
  });
});
