import type { CompanyState, EmergingIdea, EvidenceEvent, DecisionJournalEntry } from "./types";

function d(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split("T")[0];
}

// ── Evidence Events (fixtures) ──

const OXY_EVENTS: EvidenceEvent[] = [
  {
    id: "oxy-e1",
    ticker: "OXY",
    type: "insider-buy",
    direction: "positive",
    title: "Berkshire Hathaway added 2.1M shares",
    summary: "Buffett's firm increased OXY stake to 28.3%, paying ~$62 average.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(3),
    disclosureDelay: 2,
    size: 0.35,
    strength: 0.9,
    isContradiction: false,
    aiExplanation: "Berkshire's continued accumulation signals long-term conviction in OXY's carbon-capture and production strategy. The purchase represents ~$130M and follows a pattern of systematic buying during weakness.",
  },
  {
    id: "oxy-e2",
    ticker: "OXY",
    type: "capacity-announcement",
    direction: "positive",
    title: "Direct Air Capture plant reached Phase 2",
    summary: "OXY's STRATOS DAC facility hit 50% of planned capture capacity.",
    source: "usaspending",
    sourceUrl: "#",
    date: d(7),
    disclosureDelay: 1,
    size: 0.25,
    strength: 0.75,
    isContradiction: false,
    aiExplanation: "The DAC facility reaching Phase 2 validates OXY's carbon-capture thesis. Federal contracts underpin ~40% of projected revenue from this unit.",
  },
  {
    id: "oxy-e3",
    ticker: "OXY",
    type: "federal-contract",
    direction: "positive",
    title: "DOE awarded $50M carbon storage contract",
    summary: "Department of Energy contract for carbon storage monitoring.",
    source: "usaspending",
    sourceUrl: "#",
    date: d(14),
    disclosureDelay: 0,
    size: 0.15,
    strength: 0.7,
    isContradiction: false,
    aiExplanation: "DOE contracts reinforce OXY's position in carbon management. This award is consistent with the administration's CCUS funding priorities.",
  },
  {
    id: "oxy-e4",
    ticker: "OXY",
    type: "insider-sell",
    direction: "negative",
    title: "CFO sold 15,000 shares",
    summary: "CFO disposed shares under 10b5-1 plan, but amount exceeded typical plan schedule.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(5),
    disclosureDelay: 2,
    size: 0.08,
    strength: 0.45,
    isContradiction: true,
    aiExplanation: "While this was a scheduled sale, the size is 40% larger than previous quarters. Insider selling at current levels is a minor contradiction to the accumulation thesis.",
  },
  {
    id: "oxy-e5",
    ticker: "OXY",
    type: "earnings",
    direction: "positive",
    title: "Q2 EPS beat by $0.14",
    summary: "OXY reported $1.12 vs $0.98 consensus, driven by higher carbon-capture credits.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(20),
    disclosureDelay: 0,
    size: 0.2,
    strength: 0.65,
    isContradiction: false,
    aiExplanation: "The beat was driven by carbon credit revenue, not core production. This supports the thesis that carbon capture is becoming a meaningful earnings contributor.",
  },
];

const INTC_EVENTS: EvidenceEvent[] = [
  {
    id: "intc-e1",
    ticker: "INTC",
    type: "institutional-buy",
    direction: "positive",
    title: "Third Point added 3.8M shares",
    summary: "Loeb's fund initiated a significant new position in INTC.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(2),
    disclosureDelay: 45,
    size: 0.3,
    strength: 0.8,
    isContradiction: false,
    aiExplanation: "Third Point's entry is a notable activist-adjacent signal. Loeb historically pushes for operational changes and asset separation.",
  },
  {
    id: "intc-e2",
    ticker: "INTC",
    type: "federal-award",
    direction: "positive",
    title: "CHIPS Act awarded $8.5B for Ohio fab",
    summary: "Commerce Department finalized grant for Intel's Ohio semiconductor facility.",
    source: "usaspending",
    sourceUrl: "#",
    date: d(6),
    disclosureDelay: 0,
    size: 0.5,
    strength: 0.85,
    isContradiction: false,
    aiExplanation: "The CHIPS Act grant is the largest federal semiconductor award. It de-risks Intel's domestic manufacturing pivot and provides non-dilutive capital.",
  },
  {
    id: "intc-e3",
    ticker: "INTC",
    type: "revenue-acceleration",
    direction: "positive",
    title: "Foundry revenue grew 25% QoQ",
    summary: "Intel Foundry reported $612M revenue, driven by new AWS and Microsoft wafer agreements.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(10),
    disclosureDelay: 0,
    size: 0.2,
    strength: 0.7,
    isContradiction: false,
    aiExplanation: "Foundry revenue acceleration is the linchpin of Intel's turnaround. AWS and Microsoft commitments provide visible revenue for the next 3-4 quarters.",
  },
  {
    id: "intc-e4",
    ticker: "INTC",
    type: "estimate-revision",
    direction: "negative",
    title: "Q3 guidance below consensus",
    summary: "Intel guided $12.8-13.2B vs $13.8B consensus, citing PC softness.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(15),
    disclosureDelay: 0,
    size: 0.4,
    strength: 0.8,
    isContradiction: true,
    aiExplanation: "The guidance miss indicates core PC and server markets remain pressured. Foundry progress is real but too small to offset core weakness in the near term.",
  },
  {
    id: "intc-e5",
    ticker: "INTC",
    type: "insider-buy",
    direction: "positive",
    title: "CEO purchased $2.1M in open market",
    summary: "Gelsinger bought shares at $18.40, his first open-market purchase since 2021.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(4),
    disclosureDelay: 2,
    size: 0.12,
    strength: 0.6,
    isContradiction: false,
    aiExplanation: "CEO open-market purchases are rare for Gelsinger. This signals board-level confidence the stock is undervalued relative to the foundry transformation.",
  },
];

const GOOG_EVENTS: EvidenceEvent[] = [
  {
    id: "goog-e1",
    ticker: "GOOG",
    type: "institutional-buy",
    direction: "positive",
    title: "SAC Capital reported 5.2M share position",
    summary: "Point72 disclosed a new $1.4B position in Alphabet class A shares.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(4),
    disclosureDelay: 45,
    size: 0.15,
    strength: 0.5,
    isContradiction: false,
    aiExplanation: "Point72's initiation is a statistically significant signal from a fund with strong track record in tech. Position size suggests conviction.",
  },
  {
    id: "goog-e2",
    ticker: "GOOG",
    type: "federal-contract",
    direction: "positive",
    title: "DOD awarded $1.2B cloud contract to GCP",
    summary: "Joint Warfighting Cloud Capability contract awarded for secure AI infrastructure.",
    source: "usaspending",
    sourceUrl: "#",
    date: d(8),
    disclosureDelay: 0,
    size: 0.08,
    strength: 0.65,
    isContradiction: false,
    aiExplanation: "DOD cloud contracts are hard to win and harder to lose. This validates GCP's enterprise AI infrastructure and ensures 3-5 year recurring revenue.",
  },
  {
    id: "goog-e3",
    ticker: "GOOG",
    type: "upcoming-catalyst",
    direction: "neutral",
    title: "Google Cloud Next conference on Sept 24",
    summary: "Annual cloud conference where new AI product launches are expected.",
    source: "market-price",
    sourceUrl: "#",
    date: d(1),
    disclosureDelay: 0,
    size: 0.1,
    strength: 0.4,
    isContradiction: false,
    aiExplanation: "Cloud Next is a known catalyst. Market expectations are moderate — any surprise AI model release or pricing change would move the stock.",
  },
  {
    id: "goog-e4",
    ticker: "GOOG",
    type: "insider-sell",
    direction: "negative",
    title: "Sergey Brin sold $400M in scheduled trades",
    summary: "Co-founder sold under 10b5-1 plan, but accelerated pace is notable.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(6),
    disclosureDelay: 2,
    size: 0.08,
    strength: 0.35,
    isContradiction: true,
    aiExplanation: "While scheduled, Brin's accelerated selling pattern is a mild contradiction. Insiders with concentrated positions often reduce for diversification, but the pace deserves monitoring.",
  },
  {
    id: "goog-e5",
    ticker: "GOOG",
    type: "relative-strength",
    direction: "positive",
    title: "GOOG up 12% over 30 days vs QQQ +4%",
    summary: "Relative strength at 90th percentile over 3-month period.",
    source: "market-price",
    sourceUrl: "#",
    date: d(1),
    disclosureDelay: 0,
    size: 0.1,
    strength: 0.55,
    isContradiction: false,
    aiExplanation: "Sustained relative strength during a period of broad tech consolidation is a bullish divergence. AI monetization narrative is gaining traction with investors.",
  },
];

const NVO_EVENTS: EvidenceEvent[] = [
  {
    id: "nvo-e1",
    ticker: "NVO",
    type: "insider-buy",
    direction: "positive",
    title: "Board member purchased $5.2M",
    summary: "Independent director acquired shares at $98, first open-market buy in 3 years.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(5),
    disclosureDelay: 2,
    size: 0.2,
    strength: 0.8,
    isContradiction: false,
    aiExplanation: "Board-level buying after a 3-year drought is a strong insider signal. The purchase size relative to director compensation suggests genuine conviction.",
  },
  {
    id: "nvo-e2",
    ticker: "NVO",
    type: "capacity-announcement",
    direction: "positive",
    title: "FDA approved $4B API expansion facility",
    summary: "New manufacturing site in North Carolina for Wegovy/Ozempic active ingredients.",
    source: "usaspending",
    sourceUrl: "#",
    date: d(9),
    disclosureDelay: 0,
    size: 0.3,
    strength: 0.85,
    isContradiction: false,
    aiExplanation: "Supply has been the primary constraint on Wegovy revenue. This facility triples API capacity and directly removes a key bottleneck.",
  },
  {
    id: "nvo-e3",
    ticker: "NVO",
    type: "revenue-acceleration",
    direction: "positive",
    title: "Wegovy Q2 sales grew 42% YoY",
    summary: "Obesity drug revenue reached $18.2B, exceeding estimates by $1.1B.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(12),
    disclosureDelay: 0,
    size: 0.45,
    strength: 0.9,
    isContradiction: false,
    aiExplanation: "Wegovy growth remains exceptional. The beat was driven by both price and volume, indicating demand is still far from saturated.",
  },
  {
    id: "nvo-e4",
    ticker: "NVO",
    type: "estimate-revision",
    direction: "negative",
    title: "Cigna formulary change for 2026",
    summary: "Cigna placed Wegovy on Tier 3, requiring prior authorization.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(11),
    disclosureDelay: 0,
    size: 0.25,
    strength: 0.6,
    isContradiction: true,
    aiExplanation: "Tier 3 formulary placement adds friction. While Cigna covers Wegovy, prior authorization requirements could slow new prescriptions. This is a minor near-term headwind.",
  },
  {
    id: "nvo-e5",
    ticker: "NVO",
    type: "upcoming-catalyst",
    direction: "neutral",
    title: "FDA decision on oral semaglutide due Oct 15",
    summary: "Pill formulation of GLP-1 could open $30B addressable market.",
    source: "market-price",
    sourceUrl: "#",
    date: d(2),
    disclosureDelay: 0,
    size: 0.35,
    strength: 0.7,
    isContradiction: false,
    aiExplanation: "Oral semaglutide is the most important pipeline catalyst. Approval would expand the addressable market to patients who avoid injections.",
  },
];

const PFE_EVENTS: EvidenceEvent[] = [
  {
    id: "pfe-e1",
    ticker: "PFE",
    type: "institutional-buy",
    direction: "positive",
    title: "Vanguard increased stake by 8.2M shares",
    summary: "Passive giant increased position, but active funds also showed net buying.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(3),
    disclosureDelay: 45,
    size: 0.12,
    strength: 0.4,
    isContradiction: false,
    aiExplanation: "While Vanguard flows are largely passive, concurrent active fund accumulation suggests the sector rotation into pharma has begun.",
  },
  {
    id: "pfe-e2",
    ticker: "PFE",
    type: "federal-contract",
    direction: "positive",
    title: "BARDA awarded $2.4B for pandemic preparedness",
    summary: "Contract covers next-gen mRNA vaccine development and manufacturing capacity.",
    source: "usaspending",
    sourceUrl: "#",
    date: d(7),
    disclosureDelay: 0,
    size: 0.3,
    strength: 0.75,
    isContradiction: false,
    aiExplanation: "BARDA contracts provide non-dilutive R&D funding and validate Pfizer's mRNA platform beyond COVID. This extends the vaccine revenue runway.",
  },
  {
    id: "pfe-e3",
    ticker: "PFE",
    type: "revenue-acceleration",
    direction: "positive",
    title: "Oncology pipeline advanced 3 drugs to Phase 3",
    summary: "Three oncology candidates showed strong efficacy in mid-stage trials.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(14),
    disclosureDelay: 0,
    size: 0.2,
    strength: 0.65,
    isContradiction: false,
    aiExplanation: "Late-stage oncology pipeline progress is critical as Pfizer offsets post-COVID revenue declines. Three simultaneous Phase 3 entries is unusually strong.",
  },
  {
    id: "pfe-e4",
    ticker: "PFE",
    type: "insider-sell",
    direction: "negative",
    title: "CEO sold $8.2M in pre-arranged trades",
    summary: "CEO executed largest scheduled sale in four years.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(6),
    disclosureDelay: 2,
    size: 0.15,
    strength: 0.5,
    isContradiction: true,
    aiExplanation: "CEO selling is the strongest insider signal. While this was a scheduled 10b5-1 plan, the size increase from prior periods warrants attention.",
  },
  {
    id: "pfe-e5",
    ticker: "PFE",
    type: "relative-strength",
    direction: "negative",
    title: "PFE underperforming XLV by 6% over 60 days",
    summary: "Stock has weakened against healthcare sector despite pipeline progress.",
    source: "market-price",
    sourceUrl: "#",
    date: d(1),
    disclosureDelay: 0,
    size: 0.1,
    strength: 0.4,
    isContradiction: true,
    aiExplanation: "Divergence between fundamental pipeline progress and price action suggests the market is focused on post-COVID revenue gaps rather than pipeline optionality.",
  },
];

const NBIS_EVENTS: EvidenceEvent[] = [
  {
    id: "nbis-e1",
    ticker: "NBIS",
    type: "capacity-announcement",
    direction: "positive",
    title: "New AI data center cluster in Norway completed",
    summary: "Nebius commissioned a 20MW GPU cluster powered by 100% hydroelectric energy.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(1),
    disclosureDelay: 1,
    size: 0.4,
    strength: 0.85,
    isContradiction: false,
    aiExplanation: "Green AI infrastructure is a differentiating factor as hyperscalers face ESG pressure. Hydro power provides a 40% cost advantage versus competitors.",
  },
  {
    id: "nbis-e2",
    ticker: "NBIS",
    type: "institutional-buy",
    direction: "positive",
    title: "Two new institutional holders disclosed",
    summary: "D. E. Shaw and Citadel both initiated positions in Q2 13F filings.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(5),
    disclosureDelay: 45,
    size: 0.25,
    strength: 0.7,
    isContradiction: false,
    aiExplanation: "Simultaneous initiation by two multistrategy funds is a strong institutional signal. Both firms conducted extensive diligence before entering positions.",
  },
  {
    id: "nbis-e3",
    ticker: "NBIS",
    type: "revenue-acceleration",
    direction: "positive",
    title: "Q2 GPU-as-a-service revenue grew 185% YoY",
    summary: "Revenue reached $124M with gross margins expanding to 68% from 52%.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(10),
    disclosureDelay: 0,
    size: 0.5,
    strength: 0.9,
    isContradiction: false,
    aiExplanation: "Triple-digit revenue growth with expanding margins is the hallmark of a platform business reaching escape velocity. GPU-as-a-service is the highest-margin segment.",
  },
  {
    id: "nbis-e4",
    ticker: "NBIS",
    type: "federal-contract",
    direction: "positive",
    title: "EU Horizon grant of €180M for AI research",
    summary: "European Commission grant for sovereign AI infrastructure development.",
    source: "usaspending",
    sourceUrl: "#",
    date: d(12),
    disclosureDelay: 0,
    size: 0.2,
    strength: 0.6,
    isContradiction: false,
    aiExplanation: "EU sovereignty funding is a structural tailwind. European institutions prefer domestic AI infrastructure providers over US hyperscalers.",
  },
  {
    id: "nbis-e5",
    ticker: "NBIS",
    type: "insider-buy",
    direction: "positive",
    title: "Founder bought $3M in open market",
    summary: "CEO Orlovsky purchased shares at $22.50, his largest open-market buy.",
    source: "sec-edgar",
    sourceUrl: "#",
    date: d(4),
    disclosureDelay: 2,
    size: 0.18,
    strength: 0.75,
    isContradiction: false,
    aiExplanation: "Founder open-market purchases are the highest-conviction insider signal. Orlovsky's purchase signals confidence that the market undervalues the AI infrastructure buildout.",
  },
];

// ── Company States ──

export const FIXTURE_COMPANIES: Record<string, CompanyState> = {
  OXY: {
    ticker: "OXY",
    name: "Occidental Petroleum",
    latestChange: "Berkshire added 2.1M shares; DAC facility Phase 2 reached",
    implication: "Carbon capture thesis gaining momentum; institutional conviction remains strong",
    evidenceStrength: 0.78,
    contradiction: "CFO share sales exceeded normal schedule",
    nextCatalyst: "Q3 earnings report (Oct. 28)",
    newEventCount: OXY_EVENTS.length,
    events: OXY_EVENTS,
    journalEntries: [],
  },
  INTC: {
    ticker: "INTC",
    name: "Intel Corporation",
    latestChange: "Third Point entered; CHIPS Act $8.5B finalized",
    implication: "Foundry turnaround has institutional backing and government de-risking",
    evidenceStrength: 0.72,
    contradiction: "Q3 guidance below consensus; PC market weakness persists",
    nextCatalyst: "Foundry Investor Day (Sept. 12)",
    newEventCount: INTC_EVENTS.length,
    events: INTC_EVENTS,
    journalEntries: [],
  },
  GOOG: {
    ticker: "GOOG",
    name: "Alphabet Inc.",
    latestChange: "Point72 initiated $1.4B position; DOD cloud award",
    implication: "Institutional confidence in AI monetization; GCP enterprise win",
    evidenceStrength: 0.58,
    contradiction: "Brin accelerated selling pace",
    nextCatalyst: "Cloud Next conference (Sept. 24)",
    newEventCount: GOOG_EVENTS.length,
    events: GOOG_EVENTS,
    journalEntries: [],
  },
  NVO: {
    ticker: "NVO",
    name: "Novo Nordisk",
    latestChange: "Board bought $5.2M; FDA approved API expansion",
    implication: "Supply constraint easing; oral semaglutide catalyst ahead",
    evidenceStrength: 0.82,
    contradiction: "Cigna formulary change adds prescribing friction",
    nextCatalyst: "FDA oral semaglutide decision (Oct. 15)",
    newEventCount: NVO_EVENTS.length,
    events: NVO_EVENTS,
    journalEntries: [],
  },
  PFE: {
    ticker: "PFE",
    name: "Pfizer Inc.",
    latestChange: "BARDA $2.4B award; 3 oncology programs advanced",
    implication: "Pipeline progress offsetting post-COVID revenue decline",
    evidenceStrength: 0.55,
    contradiction: "CEO large scheduled sale; price weakening against sector",
    nextCatalyst: "Oncology R&D day (Oct. 3)",
    newEventCount: PFE_EVENTS.length,
    events: PFE_EVENTS,
    journalEntries: [],
  },
  NBIS: {
    ticker: "NBIS",
    name: "Nebius Group",
    latestChange: "New AI cluster online; GPU revenue +185% YoY",
    implication: "AI infrastructure platform reaching escape velocity",
    evidenceStrength: 0.85,
    contradiction: "Short interest increased to 12% of float",
    nextCatalyst: "Q3 GPUaaS revenue update (Nov. 5)",
    newEventCount: NBIS_EVENTS.length,
    events: NBIS_EVENTS,
    journalEntries: [],
  },
};

// ── Emerging Evidence ──

export const FIXTURE_EMERGING: EmergingIdea[] = [
  {
    ticker: "CRWD",
    name: "CrowdStrike Holdings",
    sector: "Cybersecurity",
    reasonCodes: [
      { code: "institutional-initiation", label: "Institutional initiation", positive: true, strength: 0.7 },
      { code: "revenue-acceleration", label: "Revenue acceleration", positive: true, strength: 0.8 },
      { code: "relative-strength", label: "Unusual relative strength", positive: true, strength: 0.65 },
      { code: "limited-history", label: "Limited operating history as public co", positive: false, strength: 0.3 },
    ],
    topEvent: {
      id: "crwd-e1",
      ticker: "CRWD",
      type: "revenue-acceleration",
      direction: "positive",
      title: "Falcon platform revenue grew 90% YoY",
      summary: "CRWD reported $892M in subscription revenue with net retention above 120%.",
      source: "sec-edgar",
      sourceUrl: "#",
      date: d(3),
      disclosureDelay: 0,
      size: 0.45,
      strength: 0.85,
      isContradiction: false,
      aiExplanation: "Falcon platform adoption is accelerating as enterprises consolidate security vendors. CRWD is winning large multi-module deals against legacy incumbents.",
    },
  },
  {
    ticker: "ONON",
    name: "On Holding AG",
    sector: "Consumer - Footwear",
    reasonCodes: [
      { code: "revenue-acceleration", label: "Revenue acceleration", positive: true, strength: 0.8 },
      { code: "institutional-initiation", label: "Institutional initiation", positive: true, strength: 0.6 },
      { code: "federal-award", label: "Upcoming catalyst", positive: true, strength: 0.5 },
      { code: "valuation", label: "Elevated valuation multiple", positive: false, strength: 0.35 },
    ],
    topEvent: {
      id: "onon-e1",
      ticker: "ONON",
      type: "revenue-acceleration",
      direction: "positive",
      title: "Q2 revenue grew 58% in Americas",
      summary: "CloudTec running shoe demand driven by women's category expansion.",
      source: "sec-edgar",
      sourceUrl: "#",
      date: d(6),
      disclosureDelay: 0,
      size: 0.3,
      strength: 0.75,
      isContradiction: false,
      aiExplanation: "Women's category has been the unlock for On's growth acceleration. The brand is expanding beyond running into lifestyle and training categories.",
    },
  },
  {
    ticker: "PLTR",
    name: "Palantir Technologies",
    sector: "Data Analytics",
    reasonCodes: [
      { code: "government-award", label: "Government award", positive: true, strength: 0.8 },
      { code: "revenue-acceleration", label: "Revenue acceleration", positive: true, strength: 0.75 },
      { code: "clustered-insider", label: "Clustered insider buying", positive: true, strength: 0.6 },
      { code: "valuation", label: "High valuation vs peers", positive: false, strength: 0.4 },
    ],
    topEvent: {
      id: "pltr-e1",
      ticker: "PLTR",
      type: "federal-contract",
      direction: "positive",
      title: "Army awarded $458M TITAN contract",
      summary: "Five-year contract for AI targeting system across all branches.",
      source: "usaspending",
      sourceUrl: "#",
      date: d(4),
      disclosureDelay: 0,
      size: 0.4,
      strength: 0.85,
      isContradiction: false,
      aiExplanation: "TITAN is Palantir's largest single contract. It validates AIP platform adoption in defense and provides a multi-year revenue base for the government segment.",
    },
  },
  {
    ticker: "RXRX",
    name: "Recursion Pharmaceuticals",
    sector: "AI Drug Discovery",
    reasonCodes: [
      { code: "clustered-insider", label: "Clustered insider buying", positive: true, strength: 0.75 },
      { code: "institutional-initiation", label: "Institutional initiation", positive: true, strength: 0.65 },
      { code: "upcoming-catalyst", label: "Upcoming catalyst", positive: true, strength: 0.6 },
      { code: "limited-history", label: "No approved products", positive: false, strength: 0.5 },
    ],
    topEvent: {
      id: "rxrx-e1",
      ticker: "RXRX",
      type: "upcoming-catalyst",
      direction: "positive",
      title: "Phase 2 readout for REC-2282 due Q4",
      summary: "AI-discovered neurofibromatosis drug enters pivotal data readout.",
      source: "sec-edgar",
      sourceUrl: "#",
      date: d(2),
      disclosureDelay: 0,
      size: 0.5,
      strength: 0.7,
      isContradiction: false,
      aiExplanation: "Positive Phase 2 data would be the first clinical validation of Recursion's AI discovery platform. The drug was wholly designed using in-house phenotypic screening.",
    },
  },
  {
    ticker: "AVAV",
    name: "AeroVironment",
    sector: "Defense - Drones",
    reasonCodes: [
      { code: "government-award", label: "Government award", positive: true, strength: 0.8 },
      { code: "revenue-acceleration", label: "Revenue acceleration", positive: true, strength: 0.7 },
      { code: "relative-strength", label: "Unusual relative strength", positive: true, strength: 0.6 },
      { code: "valuation", label: "Elevated valuation multiple", positive: false, strength: 0.3 },
    ],
    topEvent: {
      id: "avav-e1",
      ticker: "AVAV",
      type: "federal-contract",
      direction: "positive",
      title: "Army Switchblane contract expanded to $990M",
      summary: "Loitering munition system production ramped to 3x previous capacity.",
      source: "usaspending",
      sourceUrl: "#",
      date: d(5),
      disclosureDelay: 0,
      size: 0.5,
      strength: 0.9,
      isContradiction: false,
      aiExplanation: "Switchblade is becoming the standard loitering munition across all branches. The production ramp signals multi-year demand visibility well above current consensus.",
    },
  },
];

// ── Journal Fixtures ──

export const FIXTURE_JOURNAL_ENTRIES: DecisionJournalEntry[] = [
  {
    id: "j1",
    ticker: "OXY",
    thesis: "Berkshire accumulation and carbon capture infrastructure build will re-rate OXY above intrinsic value as carbon credits become a measurable earnings stream.",
    expectedCatalyst: "DOE carbon storage contracts and IRA credit monetization in Q3 earnings",
    timeHorizon: "12 months",
    invalidationCondition: "Berkshire sells any OXY shares; carbon capture revenue below $50M quarterly",
    positionSize: "8%",
    risks: "Oil price decline; carbon credit policy risk; execution on DAC technology",
    decisionDate: d(30),
    status: "active",
  },
  {
    id: "j2",
    ticker: "NBIS",
    thesis: "Nebius is the best pure-play AI infrastructure company outside of hyperscalers. GPU-as-a-service revenue growth + margin expansion will drive multiple expansion.",
    expectedCatalyst: "Q3 GPUaaS revenue >$180M with margins >70%",
    timeHorizon: "6-9 months",
    invalidationCondition: "Revenue growth <50% YoY or gross margins decline",
    positionSize: "5%",
    risks: "Small float; limited institutional research coverage; competition from hyperscalers",
    decisionDate: d(45),
    status: "active",
  },
];

// ── DEMO DATA LABEL ──

export const DEMO_LABEL = "DEMO DATA — Not real evidence";
export const FIXTURE_TICKERS = ["OXY", "INTC", "GOOG", "NVO", "PFE", "NBIS"];